routes/web.php
<?php
use App\Http\Controllers\InfokampusController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/clear',function(){
   Artisan::call('cache:clear');
   Artisan::call('config:cache');
});

Route::get('/', function () {
    return view('landing');
});


// Route::get('/login', function () {
//     return view('login');
// });

Route::get('/masuk', function () {
    return view('pages.auth.login');
});

Route::get('/landing', function () {
    return view('landing');
});

// Route::get('/pemesanan', function () {
//     return view('filter');
// });

// Route::get('/pemesanansample', function () {
//     return view('pemesanan');
// });


Route::get('/keranjang', function () {
    return view('keranjang');
});

// Route::get('/rincian', function () {
//     return view('rincian');
// });

Route::get('/pembayaran', function () {
    return view('pembayaran');
});

Route::get('/progress', function () {
    return view('progress');
});






// Route::get('auth/google',[\App\Http\Controllers\GoogleController::class,'redirectToGoogle'])->name('google.login');

// Route::get('auth/google/callback',[\App\Http\Controllers\GoogleController::class,'handleGoogleCallback'])->name('google.callback');

Auth::routes();



Route::resource('/pembeli', \App\Http\Controllers\PembeliController::class);
// Route::get('users', ['uses'=>'UserController@index', 'as'=>'users.index']);

Route::get('/pemesanan/searchnama','App\Http\Controllers\LandingController@searchnama')->middleware('auth');
Route::get('/pemesanan/searchlokasi','App\Http\Controllers\LandingController@searchlokasi')->middleware('auth');
Route::get('/pemesanan/searchopen','App\Http\Controllers\LandingController@searchopen')->middleware('auth');

Route::get('/pemesanan', [App\Http\Controllers\LandingController::class, 'pemesanan'])->name('pemesanan')->middleware('auth');
Route::get('/pemesanan/{id}', [App\Http\Controllers\LandingController::class, 'pemesananspesifik'])->name('pemesananspesifik')->middleware('auth');
Route::get('/rincian/{id}', [App\Http\Controllers\LandingController::class, 'rincianspesifik'])->name('rincianspesifik')->middleware('auth');
Route::post('/rincian/{id}', [App\Http\Controllers\LandingController::class, 'updaterincian'])->name('updaterincian')->middleware('auth');
Route::get('/pembayaran/{id}', [App\Http\Controllers\LandingController::class, 'konfirmasipembayaran'])->name('konfirmasipembayaran')->middleware('auth');
Route::get('/update-pembayaran/{id}', [App\Http\Controllers\LandingController::class, 'editpembayaran'])->name('editpembayaran')->middleware('auth');
Route::post('/update-pembayaran/{id}', [App\Http\Controllers\LandingController::class, 'updatepembayaran'])->name('updatepembayaran')->middleware('auth');
Route::get('/progress/{id}', [App\Http\Controllers\LandingController::class, 'progressproduk'])->name('progressproduk')->middleware('auth');
Route::post('/progress/{id}', [App\Http\Controllers\LandingController::class, 'updateprogress'])->name('updateprogress')->middleware('auth');
Route::get('/pemberian-rating/{id}', [App\Http\Controllers\LandingController::class, 'editrating'])->name('editrating')->middleware('auth');
Route::post('/pemberian-rating/{id}', [App\Http\Controllers\LandingController::class, 'updaterating'])->name('updaterating')->middleware('auth');



Route::get('/keranjang', [App\Http\Controllers\LandingController::class, 'keranjang'])->name('keranjang');
Route::get('/keranjang/{id}', [App\Http\Controllers\LandingController::class, 'keranjangspesifik'])->name('keranjangspesifik');


Route::get('/admin', [App\Http\Controllers\HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// Route::get('/dashboard', [\App\Http\Controllers\HomeController::class, 'dashboard'])->name('user.index');
Route::get('/dashboard', [\App\Http\Controllers\HomeController::class, 'dashboard'])->name('dashboard');
Route::get('/infokampus', [\App\Http\Controllers\HomeController::class, 'infokampus'])->name('infokampus');
Route::get('/forminfokampus', [\App\Http\Controllers\HomeController::class, 'forminfokampus'])->name('forminfokampus')->middleware('is_admin');

Route::resource('admin/informasi-toko', \App\Http\Controllers\TokoController::class)->middleware('is_admin');
Route::get('admin/informasi-pembeli', [\App\Http\Controllers\LandingController::class,'indexpembeli'])->name('indexpembeli')->middleware('is_admin');
Route::post('admin/informasi-pembeli/{id}', [\App\Http\Controllers\LandingController::class,'updateadminpembayaran'])->name('updateadminpembayaran')->middleware('is_admin');
Route::get('admin/informasi-progress', [\App\Http\Controllers\LandingController::class,'kumpulanprogress'])->name('kumpulanprogress')->middleware('is_admin');
Route::get('admin/daftar-user', [\App\Http\Controllers\LandingController::class,'daftaruser'])->name('daftaruser')->middleware('is_admin');
Route::post('admin/daftar-user/{id}', [\App\Http\Controllers\LandingController::class,'jadikanadmin'])->name('jadikanadmin')->middleware('is_admin');
Route::post('admin/informasi-progress/{id}', [\App\Http\Controllers\LandingController::class,'verifprogress'])->name('verifprogress')->middleware('is_admin');


Route::get('admin/informasi-pembeli/{id}/download', [\App\Http\Controllers\LandingController::class,'downloadfile'])->name('downloadfile')->middleware('is_admin');

resources/views/berirating.blade.php
@extends('template')
@section('content')
        <!-- Masthead-->
        <header class="masthead  text-white text-center" style = " background-color:#4696e6;">
                <div class="container d-flex flex-column">
                    <div class="row">
                        <div class="col-md-12">


                            <h3 style = "color:black;text-align:center;margin-top:30px;font-size:40px;">Terima Kasih telah bertransaksi dengan kami</h2>
                           
                            <br>
                            <center>
                          <div class="col-lg-6">

                          @if($pembelis->bintang_rating == NULL)
                          <p style = "font-size:30px;"> Silakan Pilih Rating </p>
                           <form action="{{route('updaterating',$pembelis->id)}}" enctype="multipart/form-data" method = "POST" >
                           @csrf

                            <!-- <div class="form-group">
                            <label for="bintang_rating"> Silakan Beri Rating Untuk Kami</label>
                          <select name="bintang_rating" id="bintang_rating" class = "form-control">
                          <option value="1"> <span  class = "fa fa-checked" style = "color:yellow"></span> </option>
                          <option value="2">Bintang 2</option>
                          <option value="3">Bintang 3</option>
                          <option value="4">Bintang 4</option>
                          <option value="5">Bintang 5</option>
                          </select> -->
                       
                        <div class="form-group" style = "text-align:left;">
                            <input type="checkbox" id="satu" value="1" name = "bintang_rating">
                            <label for="satu">
                            <span class="fa fa-star checked" style = "color:yellow"></span>
                            </label>
                           </div>
                           

                           <div class="form-group" style = "text-align:left;">
                            <input type="checkbox" id="dua" value="2" name = "bintang_rating">
                            <label for="dua">
                            <span class="fa fa-star checked" style = "color:yellow"></span>
                            <span class="fa fa-star checked"style = "color:yellow"></span>
                            </label>
                           </div>


                           <div class="form-group" style = "text-align:left;">
                            <input type="checkbox" id="tiga" value="3" name = "bintang_rating">
                            <label for="tiga">
                            <span class="fa fa-star checked" style = "color:yellow"></span>
                            <span class="fa fa-star checked"style = "color:yellow"></span>
                            <span class="fa fa-star checked"style = "color:yellow"></span>
                            </label>
                           </div>

                           <div class="form-group" style = "text-align:left;">
                            <input type="checkbox" id="empat" value="4" name = "bintang_rating">
                            <label for="empat">
                            <span class="fa fa-star checked" style = "color:yellow"></span>
                            <span class="fa fa-star checked"style = "color:yellow"></span>
                            <span class="fa fa-star checked"style = "color:yellow"></span>
                            <span class="fa fa-star checked"style = "color:yellow"></span>
                            </label>
                           </div>
                        

                           <div class="form-group" style = "text-align:left;">
                            <input type="checkbox" id="lima" value="5" name = "bintang_rating">
                            <label for="lima">
                            <span class="fa fa-star checked" style = "color:yellow"></span>
                            <span class="fa fa-star checked"style = "color:yellow"></span>
                            <span class="fa fa-star checked"style = "color:yellow"></span>
                            <span class="fa fa-star checked"style = "color:yellow"></span>
                            <span class="fa fa-star checked"style = "color:yellow"></span>
                            </label>
                           </div>
                        
                        




                           <br>
                           <div class="form-group">
                           <button type = "submit" class = "btn btn-success" name = "submit" id = "submit"> Submit Rating </button>
                           </div>
                           </form>

                           @elseif($pembelis->bintang_rating != NULL)
                           <br>
                           <h3 style = "font-size:40px; color:white"> Terima Kasih Atas Pilihan Rating Anda</h3>
                           <p style = "font-size:30px; color:black"> Semoga segala urusan anda dilancarkan </p>

                            @endif


                          
                           </div>
                           </center>





                </div>
            </div>
        </div>
        </header>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/keranjang.blade.php
@extends('template')
@section('content')
        <!-- Masthead-->
        <header class="masthead  text-white text-center" style = " background-color:#4696e6;">

            @foreach ( $data as $pemesan )
             

                <br>
                <br>
                <div class="container d-flex flex-column">
                    <div class="row">
                        <div class="col-md-6" style = "text-align:left;">


                            {{-- <input class="form-control" id="myInput" type="text" placeholder="Search.."> --}}
                            <h2> <strong>{{$pemesan->nama_toko}}</strong> </h2>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>



                        </div>

                        <div class="col-md-6" style = "text-align:right;">

                        </div>
                    </div>
                    <br>
                    <div class="row">

                            <div class="col-lg-12" style = "background-color: lightblue">
                                <div class="row">
                                <div class="col-md-4" style = "text-align:center;">
                                    <img src="{{asset('assets/img/file.png')}}" alt="" style = "width:75%; padding-top:20px;padding-bottom:20px;">
                                </div>

                                <div class="col-md-4" style = "text-align:left; margin-top:20px;">

                                    <ul style = "color:black">
                                        <li><p style = "font-size:20px;color:black">Nama File: {{$pemesan->nama_file}}</p></li>
                                        <!--<li><p style = "font-size:20px;color:black">Kategori : {{$pemesan->kategori}}</p></li>-->
                                        <li><p style = "font-size:20px;color:black">Jenis Kertas : {{$pemesan->jenis_kertas}}</p></li>
                                        <li><p style = "font-size:20px;color:black">Ukuran Kertas : {{$pemesan->ukuran_kertas}}</p></li>
                                        <li><p style = "font-size:20px;color:black">Jumlah Halaman : {{$pemesan->jumlah_halaman}}</p></li>
                                        <li><p style = "font-size:20px;color:black">Catatan : {{$pemesan->catatan}}</p></li>
                                    </ul>

                                </div>
                                <div class="col-md-4" style = "text-align:center;">

                                    <br>
                                    <br>

                                    @if($pemesan->file == NULL )


                                  <strong><a href="{{route('keranjangspesifik', $pemesan->id)}}" class = "btn btn-warning" style = "border-radius:100px;font-size:20px; padding-left:50px; padding-right:50px;padding-top:20px; padding-bottom:20px; margin-top:20px;margin-bottom:20px;">Anda Belum Upload File</a></strong>
                                    <br>
                                    <h3 style = "color:black"> <strong>Total : {{$pemesan->harga}}</strong> </h3>
                                    @elseif($pemesan->file != NULL && $pemesan->status_pembayaran == 0)

                                    <?php 
                                    
                                    // $pisah = explode(" - ", $pemesan->jenis_kertas);
                                    // $pisah2 = array_reverse($pisah);
                                    // $per_lembar = floatval($pisah2[0]);
                                    // $pangaos = $pemesan->jumlah_halaman;
                                    // $total = number_format($pangaos*$per_lembar)."<br>";
                                     
                                    
                                    
                                    ?>
    
                                    <h3 style = "color:black"> <strong> Rp. {{ $pemesan->harga }}</strong> </h3>
                                    <form action="{{route('pembeli.destroy', $pemesan->id)}}" method = "POST" >
                                        @csrf
                                        @method('DELETE')

                                    <button class = "btn btn-danger" type = "submit" style = "margin-bottom:10px;margin-top:10px;">Batalkan</button>
                                    <br>
                                    </form>



                                    <a href = "{{route('rincianspesifik', $pemesan->id)}}" class = "btn btn-success" type = "submit" style = "margin-bottom:10px;margin-top:10px;">Rincian Pembayaran</a>

                                    @elseif($pemesan->file != NULL && $pemesan->status_pembayaran == 1)
                                    <h3 style = "color:black"> <strong> Rp. {{ $pemesan->harga }}</strong> </h3>
                                    <a href = "{{route('konfirmasipembayaran', $pemesan->id)}}" class = "btn btn-warning" type = "submit" style = "margin-bottom:10px;margin-top:10px;">Lihat Proses Verifikasi Pembayaran</a>
                                    
                                    @elseif($pemesan->progress == NULL && $pemesan->status_pembayaran == 2)
                                    <h3 style = "color:black"> <strong> Rp. {{ $pemesan->harga }}</strong> </h3>
                                    <a href = "{{route('progressproduk', $pemesan->id)}}" class = "btn btn-dark" type = "submit" style = "margin-bottom:10px;margin-top:10px;">Pembayaran Selesai, Lihat progres</a>
                                    <form action="{{route('pembeli.destroy', $pemesan->id)}}" method = "POST" >
                                        @csrf
                                        @method('DELETE')

                                    <button class = "btn btn-danger" type = "submit" style = "margin-bottom:10px;margin-top:10px;">Hapus Order</button>
                                    <br>
                                    </form>

                                    @elseif($pemesan->progress == 2 && $pemesan->status_pembayaran == 2)
                                    <h3 style = "color:black"> <strong> Rp. {{ $pemesan->harga }}</strong> </h3>
                                    <a href = "" class = "btn btn-dark" type = "submit" style = "margin-bottom:10px;margin-top:10px;">Transaksi Selesai</a>
                                    <form action="{{route('pembeli.destroy', $pemesan->id)}}" method = "POST" >
                                        @csrf
                                        @method('DELETE')

                                    <button class = "btn btn-danger" type = "submit" style = "margin-bottom:10px;margin-top:10px;">Hapus Order</button>
                                    <br>
                                    </form>
                                    
                                    @if($pemesan->bintang_rating == NULL)
                                    
                                    <a class = "btn btn-warning" href = "{{route('updaterating',$pemesan->id)}}">Silakan Berikan Penilaian</a>
                                    @elseif($pemesan->bintang_rating != NULL)
                                            <a class = "btn btn-success" >Terima Kasih atas Penilaian Anda</a>
                                    
                                    @endif
                                    

                                    @endif


                                    



                                </div>
                            </div>

                        </div>
                    </div>










                    </div>



            </div>

 
            @endforeach
        </header>












        <!-- Footer-->
        <footer class="footer text-center" style = "background-color:#4696e6;">
            <div class="container">
                <div class="row">
                    <!-- Footer Location-->
                    <div class="col-lg-6">
                        {{-- <h4 class="text-uppercase mb-4">INFORMASI PENTING !!</h4> --}}
                        {{-- <p class="lead mb-0" style = "font-size:25px;">
                            Untuk informasi lebih lanjut dapat menghubungi :
                        </p> --}}

                        <p style = "font-size:28px; text-align:left;">Untuk informasi lebih lanjut dapat menghubungi :</p>
                        <p style = "text-align:left; font-size:28px;"> <img src="{{asset('assets/img/telephone.png')}}" alt="" style = "text-align: left;" > 081358661504  </p>
                        <p style = "text-align:left; font-size:28px;"> <img src="{{asset('assets/img/email.png')}}" alt="" style = "text-align: left;" > takprint@gmail.com  </p>

                    </div>


                    <!-- Footer About Text-->
                    <div class="col-lg-6">

                    </div>
                </div>
            </div>
        </footer>


@endsection

resources/views/keranjangspesifik.blade.php
@extends('template')
@section('content')
        <!-- Masthead-->
        <header class="masthead  text-white text-center" style = " background-color:#4696e6;">



                <br>
                <br>
                <div class="container d-flex flex-column">

                    <h4>PERHATIAN !! SILAKAN UNTUK UPLOAD FILE UNTUK PRINT !</h4>
                    
                    <br>
                    <div class="row">
                        <div class="col-md-6" style = "text-align:left;">


                            {{-- <input class="form-control" id="myInput" type="text" placeholder="Search.."> --}}

                            <h2> <strong>{{$pembelis->nama_toko}}</strong> </h2>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>



                        </div>

                        <div class="col-md-6" style = "text-align:right;">

                        </div>
                    </div>
                    <br>
                    <div class="row">

                        <div class="col-lg-12">



                            <form style = "margin-top:20px;" action = "{{route('pembeli.update', $pembelis->id)}}" method = "POST" enctype="multipart/form-data" >
                                @csrf
                                @method('PATCH')
                                <div class="form-group">
                                  <label for="file" style = "margin-bottom:50px; font-size:50px;">Silakan Upload File Anda</label>
                                  <br>
                                  <!-- <input type="text" class="form-control" id="file" name = "file"> -->
                                  <input type="file" class="form-control"  id="file" name = "file" >
                                </div>
                                <br>

                             <center>
                                {{-- <input type="submit" class="btn btn-primary" style = "font-size:30px;" name = "submit" value = "Tambah"> --}}
                                <input type="submit" class="btn btn-primary" style = "font-size:30px;" name = "submit" value = "Tambah">
                            </center>
                              </form>















                        </div>

                    </div>



            </div>



        </header>












        <!-- Footer-->
        <footer class="footer text-center" style = "background-color:#4696e6;">
            <div class="container">
                <div class="row">
                    <!-- Footer Location-->
                    <div class="col-lg-6">
                        {{-- <h4 class="text-uppercase mb-4">INFORMASI PENTING !!</h4> --}}
                        {{-- <p class="lead mb-0" style = "font-size:25px;">
                            Untuk informasi lebih lanjut dapat menghubungi :
                        </p> --}}

                        <p style = "font-size:28px; text-align:left;">Untuk informasi lebih lanjut dapat menghubungi :</p>
                        <p style = "text-align:left; font-size:28px;"> <img src="{{asset('assets/img/telephone.png')}}" alt="" style = "text-align: left;" > 081358661504  </p>
                        <p style = "text-align:left; font-size:28px;"> <img src="{{asset('assets/img/email.png')}}" alt="" style = "text-align: left;" > takprint@gmail.com  </p>

                    </div>


                    <!-- Footer About Text-->
                    <div class="col-lg-6">

                    </div>
                </div>
            </div>
        </footer>


@endsection

resources/views/pemesananspesifik.blade.php
@extends('template')

@section('content')

        <!-- Masthead-->
        <header class="masthead  text-white text-center" style = " background-color:#4696e6;">
                <div class="container d-flex flex-column">
                    <div class="row">
                        <div class="col-md-6" style = "text-align:left;">

           

                            {{-- <input class="form-control" id="myInput" type="text" placeholder="Search.."> --}}
                            <h2> <strong>{{$tokos->nama_toko}}</strong> </h2>
                            <!-- <h2> <strong>{{Auth::user()->name}}</strong> </h2> -->
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>


                            <form style = "margin-top:20px;" action = "{{route('pembeli.store')}}" method = "POST" enctype ="multipart/form-data" >
                                @csrf
                                <div class="form-group">
                                  <label for="nama_file">Nama File</label>
                                  <input type="text" class="form-control" id="nama_file" name = "nama_file">
                                </div>
                                <br>
                                <div class="form-group">
                                  <label for="telepon">Nomor HP</label>
                                  <input type="number" class="form-control" id="telepon" name = "telepon" >
                                </div>
                                <br>
                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <input type="email" class="form-control"  id="email" name = "email" >
                                  </div>
                                  <br>




                                  <div class="form-group">
                                      <label for="file">File Untuk Dicetak</label>
                                      <input type="file" class="form-control"  id="file" name = "file" >
                                    </div>





                                    <br>
                                    <!-- <div class="form-group">
                                        <label for="kategori">Kategori</label>

                                        <select class="form-control" id="kategori" name = "kategori">
                                            <option>BnW</option>
                                            <option>Warna</option>
                                            <option>Borderless</option>
                                          </select>

                                      </div> -->

                                      <br>
                                      <div class="form-group">
                                          <label for="jenis_kertas">Jenis - Ukuran Kertas - Harga</label>

                                          <select class="form-control" id="jenis_kertas" name = "jenis_kertas">
                                          @foreach($data as $kerta)
                                              <option>{{$kerta->kertas}} - {{$kerta->ukuran}} - {{$kerta->harga}} </option>
                                            @endforeach
                                              </select>
                                       
                                        </div>





                                      <!--  <br>
                                       <div class="form-group">
                                            <label for="ukurankertas">Ukuran Kertas</label>

                                            <select class="form-control" id="ukuran_kertas" name = "ukuran_kertas">
                                            @foreach($data as $ukur)
                                              <option>{{$ukur->ukuran}}</option>
                                            @endforeach
                                              </select>

                                            </select>
                                              
                                          </div> -->

                                          <br>
                                          <div class="form-group">
                                              <label for="jumlahhalaman">Jumlah Halaman</label>
                                              <input type="number" class="form-control" id="jumlah_halaman" name = "jumlah_halaman"  placeholder="">

                                            </div>





                                            <br>
                                            <div class="form-group">
                                                <label for="catatan">Catatan</label>
                                                <textarea class="form-control" id="catatan" rows="3" name = "catatan"></textarea>

                                              </div>



                                              <div class="form-group">
                                                <input name="peta_toko" id = "peta_toko" type="hidden" value="{{$tokos->peta}}">
                                              </div>


                                              <div class="form-group">
                                                <input name="nama_toko" id = "nama_toko" type="hidden" value="{{$tokos->nama_toko}}">
                                              </div>


    

                                              <div class="form-group">
                                      <input type = "hidden" name = "nama_pemesan" id = "nama_pemesan" value = "{{Auth::user()->name}}">
                                      </div>




                                        <br>


                                              <center>
                                <input type="submit" class="btn btn-primary" name = "submit" value = "Tambah">
                            </center>
                              </form>


                        </div>

                        <div class="col-md-6" style = "text-align:right;">
                            <iframe src="{{$tokos->peta}}" width="600" height="450" style="border:0; allowfullscreen="" loading="lazy"></iframe>
                            
                            
                            

              <!--<img src="{{asset('storage/Toko/'.$tokos->lambang_toko)}}" alt="" style = "width:500px;">-->
              <!--          </div>-->



                    </div>
                    <br>

            </div>
        </header>




@endsection