routes/web.php
<?php
use App\Http\Controllers\InfokampusController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/clear',function(){
   Artisan::call('cache:clear');
   Artisan::call('config:cache');
});

Route::get('/', function () {
    return view('landing');
});


// Route::get('/login', function () {
//     return view('login');
// });

Route::get('/masuk', function () {
    return view('pages.auth.login');
});

Route::get('/landing', function () {
    return view('landing');
});

// Route::get('/pemesanan', function () {
//     return view('filter');
// });

// Route::get('/pemesanansample', function () {
//     return view('pemesanan');
// });


Route::get('/keranjang', function () {
    return view('keranjang');
});

// Route::get('/rincian', function () {
//     return view('rincian');
// });

Route::get('/pembayaran', function () {
    return view('pembayaran');
});

Route::get('/progress', function () {
    return view('progress');
});






// Route::get('auth/google',[\App\Http\Controllers\GoogleController::class,'redirectToGoogle'])->name('google.login');

// Route::get('auth/google/callback',[\App\Http\Controllers\GoogleController::class,'handleGoogleCallback'])->name('google.callback');

Auth::routes();



Route::resource('/pembeli', \App\Http\Controllers\PembeliController::class);
// Route::get('users', ['uses'=>'UserController@index', 'as'=>'users.index']);

Route::get('/pemesanan/searchnama','App\Http\Controllers\LandingController@searchnama')->middleware('auth');
Route::get('/pemesanan/searchlokasi','App\Http\Controllers\LandingController@searchlokasi')->middleware('auth');
Route::get('/pemesanan/searchopen','App\Http\Controllers\LandingController@searchopen')->middleware('auth');

Route::get('/pemesanan', [App\Http\Controllers\LandingController::class, 'pemesanan'])->name('pemesanan')->middleware('auth');
Route::get('/pemesanan/{id}', [App\Http\Controllers\LandingController::class, 'pemesananspesifik'])->name('pemesananspesifik')->middleware('auth');
Route::get('/rincian/{id}', [App\Http\Controllers\LandingController::class, 'rincianspesifik'])->name('rincianspesifik')->middleware('auth');
Route::post('/rincian/{id}', [App\Http\Controllers\LandingController::class, 'updaterincian'])->name('updaterincian')->middleware('auth');
Route::get('/pembayaran/{id}', [App\Http\Controllers\LandingController::class, 'konfirmasipembayaran'])->name('konfirmasipembayaran')->middleware('auth');
Route::get('/update-pembayaran/{id}', [App\Http\Controllers\LandingController::class, 'editpembayaran'])->name('editpembayaran')->middleware('auth');
Route::post('/update-pembayaran/{id}', [App\Http\Controllers\LandingController::class, 'updatepembayaran'])->name('updatepembayaran')->middleware('auth');
Route::get('/progress/{id}', [App\Http\Controllers\LandingController::class, 'progressproduk'])->name('progressproduk')->middleware('auth');
Route::post('/progress/{id}', [App\Http\Controllers\LandingController::class, 'updateprogress'])->name('updateprogress')->middleware('auth');
Route::get('/pemberian-rating/{id}', [App\Http\Controllers\LandingController::class, 'editrating'])->name('editrating')->middleware('auth');
Route::post('/pemberian-rating/{id}', [App\Http\Controllers\LandingController::class, 'updaterating'])->name('updaterating')->middleware('auth');



Route::get('/keranjang', [App\Http\Controllers\LandingController::class, 'keranjang'])->name('keranjang');
Route::get('/keranjang/{id}', [App\Http\Controllers\LandingController::class, 'keranjangspesifik'])->name('keranjangspesifik');


Route::get('/admin', [App\Http\Controllers\HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// Route::get('/dashboard', [\App\Http\Controllers\HomeController::class, 'dashboard'])->name('user.index');
Route::get('/dashboard', [\App\Http\Controllers\HomeController::class, 'dashboard'])->name('dashboard');
Route::get('/infokampus', [\App\Http\Controllers\HomeController::class, 'infokampus'])->name('infokampus');
Route::get('/forminfokampus', [\App\Http\Controllers\HomeController::class, 'forminfokampus'])->name('forminfokampus')->middleware('is_admin');

Route::resource('admin/informasi-toko', \App\Http\Controllers\TokoController::class)->middleware('is_admin');
Route::get('admin/informasi-pembeli', [\App\Http\Controllers\LandingController::class,'indexpembeli'])->name('indexpembeli')->middleware('is_admin');
Route::post('admin/informasi-pembeli/{id}', [\App\Http\Controllers\LandingController::class,'updateadminpembayaran'])->name('updateadminpembayaran')->middleware('is_admin');
Route::get('admin/informasi-progress', [\App\Http\Controllers\LandingController::class,'kumpulanprogress'])->name('kumpulanprogress')->middleware('is_admin');
Route::get('admin/daftar-user', [\App\Http\Controllers\LandingController::class,'daftaruser'])->name('daftaruser')->middleware('is_admin');
Route::post('admin/daftar-user/{id}', [\App\Http\Controllers\LandingController::class,'jadikanadmin'])->name('jadikanadmin')->middleware('is_admin');
Route::post('admin/informasi-progress/{id}', [\App\Http\Controllers\LandingController::class,'verifprogress'])->name('verifprogress')->middleware('is_admin');


Route::get('admin/informasi-pembeli/{id}/download', [\App\Http\Controllers\LandingController::class,'downloadfile'])->name('downloadfile')->middleware('is_admin');

resources/views/admin/daftar-user.blade.php
@extends('admin.layout.app')
@section("content")

<div class="container"> 
<div class="row-content">
<br>
<div class="col-lg-12 col-md-3">
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">No</th>
      <th scope="col">Nama</th>
      <th scope="col">Email</th>
      <th scope="col">Jadikan Admin</th>


    </tr>
  </thead>
  <tbody>

  <?php $num = 1; ?>

  @foreach($user as $pengguna)

    <tr>
      <th scope="row"><?php echo $num++; ?></th>
      <td>{{$pengguna->name}}</td>
      <td>{{$pengguna->email}}</td>
      <td>

      @if($pengguna->is_admin == 0 || $pengguna->is_admin == NULL )
      <form action="{{route('jadikanadmin',$pengguna->id)}}" method = "POST" enctype="multipart/form-data">
      @csrf
      <button class = "btn btn-primary" type = "submit" name = "submit" id = "submit">Jadikan Admin</button>
      </form>
      </td>
      @elseif($pengguna->is_admin == 1)
      <button class = "btn btn-success" type = "submit" name = "submit" id = "submit" href = ""> Admin</button>

      @endif


    </tr>
    @endforeach
  </tbody>
</table>




<div class="modal fade" id="hapus" tabindex="-1" role="dialog" aria-labelledby="hapusLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Bukti Progress</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <!-- <img class="card-img-top img-cover img-fluid" src="@empty(!$pengguna->bukti_progress){{ asset('storage/Pembeli/'.$pengguna->bukti_progress) }} @else {{asset('dist/img/photo1.png')}} @endempty" alt="Card image cap" style = "object-fit: cover;    width: 100%;
            height: 15vw;"> -->
            <img class="card-img-top img-cover img-fluid" src="{{asset('storage/Pembeli/'.$pengguna->bukti_progress)}}" alt="Card image cap" style = "object-fit: cover;    width: 100%;
            height: 15vw;">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>







</div>
</div>
</div>





@endsection

resources/views/admin/editkampus.blade.php
@extends('admin.layout.app')
@section('content')
{{-- <div class="content-wrapper"> --}}
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0">Edit Informasi Kampus</h1>

</div><!-- /.col -->
</div><!-- /.row -->
</div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
<div class="container-fluid">
<!-- Small boxes (Stat box) -->
<div class="row">

<div class="col-md-6">
  <form method = "POST" action = "{{route('infokampus.update', $infokampuses->id)}}" enctype="multipart/form-data">
    @csrf
    @method('PATCH')

    <div class="form-group">
      <label for="namakampus" class="col-form-label"  >Nama Kampus </label>
      <input type="text" class="form-control" id="namakampus" name = "namakampus" value = "{{$infokampuses->namakampus}}">
    </div>
    <div class="form-group">
      <label for="alamatkampus" class="col-form-label">Alamat Kampus</label>
      {{-- <textarea class="form-control" id="alamatkampus" name = "alamatkampus" value = "{{$infokampuses->alamatkampus}}"></textarea> --}}
      <input type="text" class="form-control" id="alamatkampus" name = "alamatkampus" value = "{{$infokampuses->alamatkampus}}">
    </div>

    <div class="form-group">
        <label for="alamatkampus" class="col-form-label">Upload File</label>
        {{-- <textarea class="form-control" id="alamatkampus" name = "alamatkampus" value = "{{$infokampuses->alamatkampus}}"></textarea> --}}
        <input type="file" class="form-control" name="lambangkampus" id = "lambangkampus" value="{{$infokampuses->lambangkampus}}">
      </div>

      <input type="submit" class = "btn btn-primary" value="Simpan" placeholder="Simpan">
    </form>


    </div>










</div>
<!-- /.row (main row) -->
</div><!-- /.container-fluid -->
</section>
<!-- /.content -->
</div>
@endsection

resources/views/admin/editkampusdua.blade.php
@extends('admin.layoututama')
@section('content')
{{-- <div class="content-wrapper"> --}}
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0">Edit Informasi Kampus</h1>

</div><!-- /.col -->
</div><!-- /.row -->
</div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
<div class="container-fluid">
<!-- Small boxes (Stat box) -->
<div class="row">

<div class="col-md-6">
  <form method = "POST" action = "{{route('infokampus.update', $infokampuses->id)}}" enctype="multipart/form-data">
    @csrf
    @method('PATCH')

    <div class="form-group">
      <label for="namakampus" class="col-form-label"  >Nama Kampus </label>
      <input type="text" class="form-control" id="namakampus" name = "namakampus" value = "{{$infokampuses->namakampus}}">
    </div>
    <div class="form-group">
      <label for="alamatkampus" class="col-form-label">Alamat Kampus</label>
      {{-- <textarea class="form-control" id="alamatkampus" name = "alamatkampus" value = "{{$infokampuses->alamatkampus}}"></textarea> --}}
      <input type="text" class="form-control" id="alamatkampus" name = "alamatkampus" value = "{{$infokampuses->alamatkampus}}">
    </div>

    <div class="form-group">
        <label for="alamatkampus" class="col-form-label">Upload File</label>
        {{-- <textarea class="form-control" id="alamatkampus" name = "alamatkampus" value = "{{$infokampuses->alamatkampus}}"></textarea> --}}
        <input type="file" class="form-control" name="lambangkampus" id = "lambangkampus" value="{{$infokampuses->lambangkampus}}">
      </div>

      <input type="submit" class = "btn btn-primary" value="Simpan" placeholder="Simpan">
    </form>


    </div>










</div>
<!-- /.row (main row) -->
</div><!-- /.container-fluid -->
</section>
<!-- /.content -->
</div>
@endsection

resources/views/admin/edittoko.blade.php
@extends('admin.layout.app')
@section('content')
{{-- <div class="content-wrapper"> --}}
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0">Edit Informasi _toko</h1>

</div><!-- /.col -->
</div><!-- /.row -->
</div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
<div class="container-fluid">
<!-- Small boxes (Stat box) -->
<div class="row">

<div class="col-md-6">
  <form method = "POST" action = "{{route('informasi-toko.update', $tokos->id)}}" enctype="multipart/form-data">
    @csrf
    @method('PATCH')

    <div class="form-group">
      <label for="nama_toko" class="col-form-label"  >Nama Toko </label>
      <input type="text" class="form-control" id="nama_toko" name = "nama_toko" value = "{{$tokos->nama_toko}}">
    </div>
    <div class="form-group">
      <label for="alamat_toko" class="col-form-label">Alamat Toko</label>
      {{-- <textarea class="form-control" id="alamat_toko" name = "alamat_toko" value = "{{$tokos->alamat_toko}}"></textarea> --}}
      <input type="text" class="form-control" id="alamat_toko" name = "alamat_toko" value = "{{$tokos->alamat_toko}}">
    </div>

    <div class="form-group">
        <label for="alamat_toko" class="col-form-label">Upload File</label>
        {{-- <textarea class="form-control" id="alamat_toko" name = "alamat_toko" value = "{{$tokos->alamat_toko}}"></textarea> --}}
        <input type="file" class="form-control" name="lambang_toko" id = "lambang_toko" value="{{$tokos->lambang_toko}}">
      </div>


      <div class="form-group">
        <label for="jenis_kertas" class="col-form-label">Jenis Kertas</label>
        <textarea name="jenis_kertas" class = "form-control" id="jenis_kertas" cols="30" rows="10" value = "{{$tokos->jenis_kertas}}">{{$tokos->jenis_kertas}}</textarea>
      </div>



      <div class="form-group">
        <label for="ukuran_kertas" class="col-form-label">Ukuran Kertas</label>
        <textarea name="ukuran_kertas" class = "form-control" id="ukuran_kertas" cols="30" rows="10" value = "{{$tokos->ukuran_kertas}}">{{$tokos->ukuran_kertas}}</textarea>
      </div>





      <div class="form-group">
        <label for="harga" class="col-form-label">Harga</label>
        <textarea name="harga" class = "form-control" id="harga" cols="30" rows="10" value = "{{$tokos->harga}}">{{$tokos->harga}}</textarea>
      </div>
      
      
      
            <div class="form-group">
        <label for="peta" class="col-form-label">Link Lokasi Peta</label>
        <textarea name="peta" class = "form-control" id="peta" cols="30" rows="10" value = "{{$tokos->harga}}">{{$tokos->peta}}</textarea>
      </div>
      
      
      

      <div class="form-group">
        <label for="waktu_buka" class="col-form-label">Waktu Buka</label>
        <input type="time" name ="waktu_buka" id="waktu_buka" class ="form-control">
      </div>

      <div class="form-group">
        <label for="waktu_tutup" class="col-form-label">Waktu Tutup</label>
        <input type="time" name ="waktu_tutup" id="waktu_tutup" class ="form-control">
      </div>

        <br>

      <div class="form-group">
      <p> <strong>Untuk Kondisi Toko, Jika ada perubahan jam ( tidak sesuai jadwal yang sudah ditetapkan ), silakan untuk diisi kondisi di bawah ini</strong> </p>
      </div>

      <div class="form-group">
        <label for="open" class="col-form-label">Kondisi Toko</label>
        <select name="open" id="open" class = "form-control">
            <option disabled selected value> -- Pilih Kondisi Toko -- </option>
            <option value="open">Open</option>
            <option value="close">Close</option>
        </select>
      </div>

      <input type="submit" class = "btn btn-primary" value="Simpan" placeholder="Simpan">
    </form>


    </div>










</div>
<!-- /.row (main row) -->
</div><!-- /.container-fluid -->
</section>
<!-- /.content -->
</div>
@endsection

resources/views/admin/toko.blade.php
@extends('admin.layout.app')
@section("content")

{{-- <div class="content-wrapper"> --}}
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Daftar Toko</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item">     <a type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Tambahkan Toko</a></li>
              {{-- <li class="breadcrumb-item active">Dashboard v1</li> --}}
              {{-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Tambahkan Toko</button> --}}
            </ol>


            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Toko Baru</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <form method = "POST" action = "{{route('informasi-toko.store')}}">
                        @csrf
                        <div class="form-group">
                          <label for="nama_toko" class="col-form-label"  >Nama Toko </label>
                          <input type="text" class="form-control" id="nama_toko" name = "nama_toko">
                        </div>
                        <div class="form-group">
                          <label for="alamat_toko" class="col-form-label">Alamat Toko</label>
                          {{-- <textarea class="form-control" id="alamat_toko" name = "alamat_toko"></textarea> --}}
                          <input type="text" class="form-control" id="alamat_toko" name = "alamat_toko">
                        </div>


                        {{-- <div class="form-group">
                            <label for="jenis_kertas" class="col-form-label">Jenis Kertas</label>
                            <select name="jenis_kertas" id="jenis_kertas" class = "form-control">
                                <option disabled selected value> -- Pilih Jenis Kertas -- </option>
                                <option value="HVS">HVS</option>
                                <option value="Manilla">Manilla</option>
                                <option value="Bufallo">Bufallo</option>
                                <option value="Concorde">Concorde</option>
                            </select>

                          </div> --}}

                          <div class="form-group">
                            <label for="jenis_kertas" class="col-form-label">Jenis Kertas</label>
                            <textarea name="jenis_kertas" class = "form-control" id="jenis_kertas" cols="30" rows="10"></textarea>
                          </div>



                          <div class="form-group">
                            <label for="ukuran_kertas" class="col-form-label">Ukuran Kertas</label>
                            <textarea name="ukuran_kertas" class = "form-control" id="ukuran_kertas" cols="30" rows="10"></textarea>
                          </div>

                          <div class="form-group">
                            <label for="harga" class="col-form-label">Harga</label>
                            <textarea name="harga" class = "form-control" id="harga" cols="30" rows="10"></textarea>
                          </div>

                          <div class="form-group">
                            <label for="open" class="col-form-label">Kondisi Toko</label>
                            <select name="open" id="open" class = "form-control">
                                <option disabled selected value> -- Pilih Kondisi Toko -- </option>
                                <option value="Open">Open</option>
                                <option value="Close">Close</option>
                            </select>
                          </div>

                          <div class="form-group">
                            <label for="waktu_buka" class="col-form-label">Waktu Buka</label>
                            <textarea name="waktu_buka" class = "form-control" id="waktu_buka" cols="30" rows="10"></textarea>
                          </div>

                          <div class="form-group">
                            <label for="waktu_tutup" class="col-form-label">Waktu Tutup</label>
                            <textarea name="waktu_tutup" class = "form-control" id="waktu_tutup" cols="30" rows="10"></textarea>
                          </div>







                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      {{-- <button type="button" class="btn btn-primary" type = "submit" name = "submit">Kirim Data</button> --}}
                      <input type="submit" class = "btn btn-primary" value="Simpan" placeholder="Simpan">
                    </div>
                </form>
                  </div>
                </div>
              </div>



          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">



@foreach($tokos as $infotoko)



   <!-- Area Chart -->
   <div class="col-md-4 col-mb-3">
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary"></h6>
            {{-- <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                </a>
            </div> --}}
        </div>


        <!-- Card Body -->
        <div class="card-body" >
            {{-- <img class="card-img-top img-cover img-fluid" src="{{asset('dist/img/photo1.png')}}" alt="Card image cap" style = "object-fit: cover;    width: 100%;
            height: 15vw;"> --}}
            <img class="card-img-top img-cover img-fluid" src="@empty(!$infotoko->lambang_toko){{ asset('storage/Toko/'.$infotoko->lambang_toko) }} @else {{asset('dist/img/photo1.png')}} @endempty" alt="Card image cap" style = "object-fit: cover;    width: 100%;
            height: 15vw;">


            <div class="card-body">
            {{-- <h5 class="card-title m-0 font-weight-bold text-dark" style = "text-align:center;">Ieu Aink</h5> --}}
            
        <center><h5 class="card-title m-0 font-weight-bold text-dark" style = "text-align:center;">{{$infotoko->nama_toko}}</h5></center>
        
         <center>   <p class="card-text" style = "margin-top:5px;margin-bottom:5px;">{{$infotoko->alamat_toko}}</p> </center>
         
         
         
         
                        <?php 
                        date_default_timezone_set('Asia/Jakarta');
                        $time_default = date('H:i:s');
                        $time_buka = $infotoko->waktu_buka;
                        $time_tutup = $infotoko->waktu_tutup;


                        ?>

                        <?php
                        
                        if($time_buka < $time_default && $time_tutup > $time_default )
                        {
                        
                            ?>
         
         
         
         
         
         <center> <strong><h6 class="card-text" style = "margin-top:5px;margin-bottom:5px;">Buka</h6> </strong> </center>
         
                        <?php }

                        else if ($time_tutup == NULL && $time_buka == NULL) {
                        ?>

         <center> <strong><h6 class="card-text" style = "margin-top:5px;margin-bottom:5px;">Tutup</h6> </strong> </center>
         
         
                       <?php }
                       else {
                       ?>
               <center> <strong><h6 class="card-text" style = "margin-top:5px;margin-bottom:5px;">Tutup</h6> </strong> </center>        
                       
                      
                       <?php } ?>
                       
         
         
         
         
         {{-- <center> <a href="#" style = "margin-bottom:10px;margin-top:10px;" class="btn btn-success">Edit Toko</a></center> --}}







         <center>
            <form action="{{ route('informasi-toko.destroy',$infotoko->id) }}" method="POST">
             @csrf
             @method('DELETE')
{{--
             <a href="{{route('infoToko.edit',$class->id)}}" style = "margin-bottom:10px;margin-top:10px;" class="btn btn-success">Edit Toko</a> --}}
               <button class = "btn btn-danger" type = "submit" style = "margin-bottom:10px;margin-top:10px;">Hapus Toko</button>
               {{-- <a type="button" class="btn btn-primary" data-toggle="modal" data-target="#EditModal">Edit Toko</a> --}}
               <a href="{{url('/pemesanan')}}" style = "margin-bottom:10px;margin-top:10px; margin-left:5px;margin-right:5px;" class="btn btn-primary">Lihat Toko</a>
               <a href="{{route('informasi-toko.edit',$infotoko->id)}}" style = "margin-bottom:10px;margin-top:10px;" class="btn btn-success">Edit Toko</a>

            </form>

              </center>

            </div>


        </div>
    </div>
</div>


@endforeach












        </div>
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
@endsection